# Generated by Django 4.1.7 on 2023-04-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='swiped_left',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='swiped_right',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
