# Generated by Django 4.1.7 on 2023-04-01 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Matching', '0002_matches_swiped_left_matches_swiped_right'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
