# Generated by Django 4.1.7 on 2023-04-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Matching', '0003_alter_matches_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='created_at',
        ),
    ]
