# Generated by Django 4.1.7 on 2023-04-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matching', '0004_remove_matches_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Global_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binary_question_similarity_mean', models.FloatField()),
                ('binary_question_dissimilarity_mean', models.FloatField()),
                ('binary_question_similarity_std', models.FloatField()),
                ('binary_question_dissimilarity_std', models.FloatField()),
                ('movies_number_of_similarity_mean', models.FloatField()),
                ('movies_number_of_similarity_std', models.FloatField()),
                ('books_number_of_similarity_mean', models.FloatField()),
                ('books_number_of_similarity_std', models.FloatField()),
                ('music_number_of_similarity_mean', models.FloatField()),
                ('music_number_of_similarity_std', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='MBTI',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='animal',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='datechar',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='daynight',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='dob',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='edu',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='interests',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='minmax',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='mothertongue',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='movie',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='music',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='partner_age_high',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='partner_age_low',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='partner_edu',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='partner_gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='partner_mothertongue',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='partner_profession',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='partner_religion',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='pob',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='profession',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='relationshiptype',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='religion',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='tob',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
