# Generated by Django 4.1.7 on 2023-04-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matching', '0006_matches_match_score_western_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='book',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
