# Generated by Django 4.1.7 on 2023-04-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matching', '0007_questions_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='Matching/'),
        ),
    ]
