# Generated by Django 4.1.7 on 2023-04-02 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Matching', '0008_questions_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='profile_photo',
        ),
    ]
